services:
  # MARK: PROD
  dictionary-bot:
    container_name: dictionary-bot
    profiles: ["prod"]
    build:
      context: ./bot
      args:
        ENV: prod
    env_file: "./bot/.env"
    command: ["uv", "run", "./app/main.py"]
    volumes:
      - ./bot/app/:/app/app/
      - ./files/:/app/files/

  # MARK: DEV
  bot-dev:
    container_name: bot-dev
    profiles: ["dev"]
    build:
      context: ./bot
      args:
        ENV: dev
    env_file: "./bot/.env"
    command: ["uv", "run", "./app/main.py"]
    volumes:
      - ./bot/app/:/app/app/
      - ./files/:/app/files/
