"""Add translations.view_count field

Revision ID: 6122f4ca5541
Revises: ad96bc8ce641
Create Date: 2025-08-08 11:12:00.287528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6122f4ca5541"
down_revision: Union[str, None] = "ad96bc8ce641"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "translations",
        sa.Column(
            "view_count",
            sa.Integer(),
            nullable=False,
            comment="Количество просмотров перевода",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("translations", "view_count")
    # ### end Alembic commands ###
