"""Add translations table

Revision ID: ad96bc8ce641
Revises:
Create Date: 2025-08-08 10:25:50.303686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad96bc8ce641"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source", sa.String(length=255), nullable=False, comment="Исходный текст"
        ),
        sa.Column(
            "translation", sa.Text(), nullable=False, comment="Переведённый текст"
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Дата и время создания записи о городе",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Дата и время изменения записи о городе",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_translations")),
    )
    op.create_index(op.f("ix_translations_id"), "translations", ["id"], unique=False)
    op.create_index(
        op.f("ix_translations_source"), "translations", ["source"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_translations_source"), table_name="translations")
    op.drop_index(op.f("ix_translations_id"), table_name="translations")
    op.drop_table("translations")
    # ### end Alembic commands ###
